### ISSUE TITLE
Wrist position Bug

### ISSUE THREAD

**Issue by IngenVR** [alloystorm/dvvr#17] opened 2019-12-23 13:51 UTC
wrist sinking into chest.
The wrist is placed behind more than the original motion.
![add-1](https://user-images.githubusercontent.com/58618176/71360254-8a304300-25d2-11ea-8261-badd8c3db635.jpg)
![add-2](https://user-images.githubusercontent.com/58618176/71360265-94524180-25d2-11ea-8b28-2af88953b236.jpg)
![add-3](https://user-images.githubusercontent.com/58618176/71360277-9f0cd680-25d2-11ea-8646-df58641295d9.png)
![add-4](https://user-images.githubusercontent.com/58618176/71360280-a207c700-25d2-11ea-98b3-8e60634d5c37.png)
![Conqueror-1](https://user-images.githubusercontent.com/58618176/71360282-a502b780-25d2-11ea-8b5e-bf97100ab41d.jpg)
![Conqueror-2](https://user-images.githubusercontent.com/58618176/71360284-a7651180-25d2-11ea-96eb-914b8325f8d7.jpg)

**Comment by alloystorm** [comment] 2019-12-24 10:16
Thank you so much for the detailed comparison images. We will have a good look at this.

**Comment by alloystorm** [comment] 2019-12-27 05:53
We figured it out. Fix will be available in the next release.

**Comment by alloystorm** [comment] 2019-12-30 00:36
Fixed in 0.4.4

**Comment by Kamakura81** [comment] 2019-12-30 12:44
Thanks for fixing.
But, I think the fix is ​​not enough.
How about adding wrist and elbow correction items to the pose tab？
or add the original uncorrected motion option.
![9841984](https://user-images.githubusercontent.com/58618176/71582389-65494c00-2b4d-11ea-9109-56067c99bb09.png)
![ad4 4-006](https://user-images.githubusercontent.com/58618176/71582295-eb18c780-2b4c-11ea-863d-332aa21a2da4.png)
![ad4 4-003](https://user-images.githubusercontent.com/58618176/71582303-f2d86c00-2b4c-11ea-9dca-bfbc08312d1a.png)
![ad4 4-002](https://user-images.githubusercontent.com/58618176/71582314-fe2b9780-2b4c-11ea-9f9c-13a40dbe4428.png)
![ad4 4-001](https://user-images.githubusercontent.com/58618176/71582318-01268800-2b4d-11ea-905b-9634e95f404a.png)
![ad4 4-005](https://user-images.githubusercontent.com/58618176/71582325-07b4ff80-2b4d-11ea-8141-bd2b8743bfb9.png)
![ad4 4-004](https://user-images.githubusercontent.com/58618176/71582327-0b488680-2b4d-11ea-86e7-48458ea7ee0f.png)

**Comment by Kamakura81** [comment] 2019-12-30 12:50
Thanks for fixing.
But, I think the fix is ​​not enough.
How about adding wrist and elbow correction items to the pose tab？
or add the original uncorrected motion option.

![ad4 4-003](https://user-images.githubusercontent.com/58618176/71582574-2cf63d80-2b4e-11ea-8d9f-c22499330da7.png)
![ad4 4-004](https://user-images.githubusercontent.com/58618176/71582585-3a132c80-2b4e-11ea-8b14-3638989252ad.png)
![ad4 4-002](https://user-images.githubusercontent.com/58618176/71582592-3da6b380-2b4e-11ea-8003-0f291864691e.png)
![ad4 4-001](https://user-images.githubusercontent.com/58618176/71582595-40a1a400-2b4e-11ea-9e66-6c454d0d79c9.png)
![ad4 4-005](https://user-images.githubusercontent.com/58618176/71582597-45feee80-2b4e-11ea-8f0f-d5bffbd1057c.png)
![ad4 4-006](https://user-images.githubusercontent.com/58618176/71582602-47c8b200-2b4e-11ea-982a-aecba2fb9fb5.png)

**Comment by alloystorm** [comment] 2020-01-17 05:01
I see, the root cause is that each model have different initial arm positions and they might not match the initial pose of the motion. 
I guess there is no one size fits all solution. I'll consider adding custom control of the initial positions to fine tune the motion. 
Thanks again for your detailed comparison screenshots.

**Comment by IngenVR** [comment] 2020-05-28 15:47
Is it possible to separate the right and left arm bending settings?
And could you add the same settings to shoulders and wrists?

**Comment by alloystorm** [comment] 2020-09-01 05:30
Glad to announce that this is now fixed in 0.7.1. Please have a try and see if the latest version works for you.

**Closed** 2020-09-03 12:46 UTC
