### ISSUE TITLE
Another unloading model

### ISSUE THREAD

**Issue by hboxgames** [alloystorm/dvvr#131] opened 2021-08-15 22:48 UTC
Hi !

Thanks for the great feature as always !

1- Again, found a model that just doesn't load up in the soft, although I can see it without problem with pmx editor.
https://we.tl/t-AgTcMJunsA

2- Also, it may already be flagged but the dynamics have problem of not being scaled with the character. Since I use the scale feature a lot I noticed it, but I guess it's a quick fix since you didn't have this before ? 

3- Not sure if this is something that can be sorted out really, but for "non-mocap" motions, that people made basically, even the relatively high quality ones, they tend to struggle being as correct as they would be in MMD. The little differences would make center move weird and/or snap knees etc.
Here's a motion that is widely used and have great quality :
https://we.tl/t-2HyKY1YAex
and an example of how the motion should look 
https://www.youtube.com/watch?v=9ZvjEjX5XXE

Maybe you're already on the try to get these motion difference fixed !

Anyway thanks again for the great work !

**Comment by alloystorm** [comment] 2021-08-20 01:32
Thanks a lot, will have a look.

**Comment by alloystorm** [comment] 2021-11-07 00:56
Forgot to update this issue.

The Wiggle Wiggle motion issue can be addressed with the "Center Offset" option in the motion settings. 

Physics after scaling has been fixed in the 1.1.1 release. 

The issue with that particular model is work in progress, there is something wrong with one of the morphs. We can surpress  that problem easily but will look further to find the root cause. 

Closing this issue now and will merge the model issue with the other model related issue.

**Closed by alloystorm** 2021-11-07 00:56 UTC
