### ISSUE TITLE
Model Replace Bugs

### ISSUE THREAD

**Issue by Terell2018** [alloystorm/dvvr#14] opened 2019-12-05 11:55 UTC
I just discover a bugs in the dvvr 0.4.1. sometime when i click on replace it causes a bugs in the model. it happened with all the model. even click on remove the model and reload a model still have a bugs. sorry i am not good at explain.

![Capture 1] https://user-images.githubusercontent.com/49305586/70232473-870c0a80-172a-11ea-9097-aaa9ed7d4f12.PNG

![Capture 2] https://user-images.githubusercontent.com/49305586/70232967-93449780-172b-11ea-9742-301d75a1ccdc.PNG

**Comment by alloystorm** [comment] 2019-12-05 21:16
Thank you, we've noticed that too. Still investigating. 

It seems only happens on PMX models.

**Comment by Terell2018** [comment] 2019-12-10 18:24
Just wonder is it have something to do with the xnalara bone break the pmx bone.

**Comment by alloystorm** [comment] 2019-12-13 13:22
Fixed in 0.4.3, please update and let us know if the problem is solved.

**Comment by Terell2018** [comment] 2019-12-13 20:01
I just try it out and it fixed even with the replace model.

**Closed** 2019-12-13 23:52 UTC
