### ISSUE TITLE
Actor Scale Bug

### ISSUE THREAD

**Issue by Kamakura81** [alloystorm/dvvr#15] opened 2019-12-07 12:33 UTC
When load a PMX model and change Actor scale, breaks the model.
I think that the size of the material to which physics is applied does not change.
![scale1 0mdoel1](https://user-images.githubusercontent.com/58618176/70374706-ffe0b180-1938-11ea-90b8-86f852414dcb.jpg)
![scale1 0model2](https://user-images.githubusercontent.com/58618176/70374708-02dba200-1939-11ea-88f3-180b09826e6f.jpg)
![scale1 0model3](https://user-images.githubusercontent.com/58618176/70374709-04a56580-1939-11ea-8829-bfaf7873dd45.jpg)

**Comment by alloystorm** [comment] 2019-12-08 13:30
Thanks, will fix this in the next release.

**Comment by alloystorm** [comment] 2019-12-13 13:22
Fixed in 0.4.3, please update and let us know if the problem is solved.

**Comment by Kamakura81** [comment] 2019-12-13 22:41
I confirmed the fixed issue.
Thank you!

**Closed** 2019-12-13 22:41 UTC
