### ISSUE TITLE
Stages folder

### ISSUE THREAD

**Issue by Terell2018** [alloystorm/dvvr#20] opened 2020-01-13 21:05 UTC
Where do i put stages folder in because when i put stages folder inside the content folder it not show.

**Comment by alloystorm** [comment] 2020-01-16 09:59
The folder structure should be like this:

![Capture](https://user-images.githubusercontent.com/51807035/72514741-ff75f780-38a2-11ea-938d-33084ab537b1.PNG)

**Comment by alloystorm** [comment] 2020-01-16 10:00
Also you can find example in our content package. Let me know if you are still having issue.

**Comment by Terell2018** [comment] 2020-01-16 22:14
I just trying it but it still not showing up.

**Comment by alloystorm** [comment] 2020-01-17 03:32
Which version are you running? 
The custom stage feature is currently only in the private builds.

**Comment by chengsta** [comment] 2020-01-17 06:14
you must name the folders EXACTLY as shown.  NO CAPS

**Comment by Terell2018** [comment] 2020-01-17 06:25
i am uses dvvr 0.4.4 public build.

**Comment by Terell2018** [comment] 2020-01-17 06:33
Maybe i just wait till release in public.

**Comment by alloystorm** [comment] 2020-02-03 03:07
Closing this since it is not a bug :D

**Closed by alloystorm** 2020-02-03 03:07 UTC
