### ISSUE TITLE
Stages not showing up 0.6  Cache file inside.

### ISSUE THREAD

**Issue by chengsta** [alloystorm/dvvr#49] opened 2020-04-06 02:33 UTC
Hello, so it seems I'm not the only one with the problems with stages not being loaded.  Here is the link to the cache file you requested:  https://drive.google.com/open?id=11nEJb4YVaKdviRFgfQPXfpuOA8WEtmys

and here is the directory that I keep my content in:
X:\DVVR hdrp 0.6\Content\scenes
X:\DVVR hdrp 0.6\Content\stages
X:\DVVR hdrp 0.6\Content\motion
X:\DVVR hdrp 0.6\Content\actors

As you can see, they're all in the same directory, and it loads everything else...just not the stages.  I have not changed the directory ever since you started the DVVR project.

**Comment by alloystorm** [comment] 2020-04-06 11:37
Thanks for the upload. 

I can reproduce your issue and found a quick workaround.

Basically you can move your content folder further away from your executables folder and it should work fine. Either to a different drive or a couple of levels up. 

The root cause is when the content is close to the executables, it uses a relative path to locate the content and there is a bug when loading stage from a relative path that it repeated content folder twice in the path (./content/stages/xxx becomes ./content/content/stages/xxx), therefore the file couldn't be found. 

We'll fix this but for now, the above-mentioned workaround should allow you to load stages.

**Comment by alloystorm** [comment] 2020-04-06 13:41
Fixed in 0.6a

**Closed** 2020-04-09 03:54 UTC
Labels: bug
