### ISSUE TITLE
Multiple Sex Motion 3 issues

### ISSUE THREAD

**Issue by TretanJonas** [alloystorm/dvvr#317] opened 2024-01-14 17:36 UTC
sex motion 3 is looking broken?. 2 male actor are align to female actor 1.
i thought Dev already knowing this but after update from 1.5.1.1150 to 2024.1 the issues remains
(im just casually enjoying there stuff and finding quite a bug from there)

![1 5 0 1132](https://github.com/alloystorm/dvvr/assets/38006312/f5b01a3c-b30d-4c8c-a1ab-ac0aea62612f)
![2024 1](https://github.com/alloystorm/dvvr/assets/38006312/a342b464-45e5-43c1-a6c8-99b56ab53af7)

**Comment by TretanJonas** [comment] 2024-01-14 17:38
as again the issues doesn't bothered me even on version 1.5.1.1150 for month

**Comment by alloystorm** [comment] 2024-02-07 06:07
So do you mean the issue is that the "dick" bends to the side? Does this happen only to that model?

**Comment by TretanJonas** [comment] 2024-02-10 14:26
huh no just put 2 female and 2 male actor and have it all sex motion 3 (2 female, 2 male)

2 of the male will just bend toward the one of the Female

(just have it that i guess cannot describe the details of it)

**Comment by alloystorm** [comment] 2024-04-03 10:29
This is fixed in 2024.4

**Closed** 2024-04-06 07:03 UTC
Labels: fixed
